const users = [
  {
    id: "1",
    username: "john_doe",
    name: "John Doe",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "Tech enthusiast and coffee lover.",
  },
  {
    id: "2",
    username: "jane_smith",
    name: "Jane Smith",
    image: "https://picsum.photos/seed/jane/200.jpg",
    bio: "Traveler and food blogger.",
  },
  {
    id: "3",
    username: "mike_brown",
    name: "Mike Brown",
    image: "https://picsum.photos/seed/mike/200.jpg",
    bio: "Fitness coach and entrepreneur.",
  },
  {
    id: "4",
    username: "sara_white",
    name: "Sara White",
    image: "https://picsum.photos/seed/sara/200.jpg",
    bio: "Photographer and nature lover.",
  },
  {
    id: "5",
    username: "emma_green",
    name: "Emma Green",
    image: "https://picsum.photos/seed/emma/200.jpg",
    bio: "Writer and bookworm.",
  },
  {
    id: "6",
    username: "alex_jones",
    name: "Alex Jones",
    image: "https://picsum.photos/seed/alex/200.jpg",
    bio: "Musician and dreamer.",
  },
  {
    id: "7",
    username: "nina_wilson",
    name: "Nina Wilson",
    image: "https://picsum.photos/seed/nina/200.jpg",
    bio: "Designer and artist.",
  },
  {
    id: "8",
    username: "daniel_kim",
    name: "Daniel Kim",
    image: "https://picsum.photos/seed/daniel/200.jpg",
    bio: "Developer and gamer.",
  },
  {
    id: "9",
    username: "lisa_ray",
    name: "Lisa Ray",
    image: "https://picsum.photos/seed/lisa/200.jpg",
    bio: "Health coach and yogi.",
  },
  {
    id: "10",
    username: "tom_clark",
    name: "Tom Clark",
    image: "https://picsum.photos/seed/tom/200.jpg",
    bio: "Marketer and adventurer.",
  },
];

const posts = [
  {
    id: "101",
    createdAt: "2025-06-01T10:00:00Z",
    content: "Hello world! This is my first post.",
    user_id: "1",
    user: users[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "102",
    createdAt: "2025-05-01T11:00:00Z",
    content: "Just finished an epic road trip!",
    user_id: "2",
    user: users[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "103",
    createdAt: "2025-05-01T12:00:00Z",
    content: "Workout goals: smashed 💪",
    user_id: "3",
    user: users[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "104",
    createdAt: "2025-05-01T13:00:00Z",
    content: "Captured this breathtaking view!",
    user_id: "4",
    user: users[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "105",
    createdAt: "2025-05-01T14:00:00Z",
    content: "Nothing beats a good book and coffee.",
    user_id: "5",
    user: users[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "106",
    createdAt: "2025-05-01T15:00:00Z",
    content: "@john_doe that's awesome!",
    user_id: "6",
    user: users[5],
    parent_id: "101",
    parent: null,
    replies: [],
  },
  {
    id: "107",
    createdAt: "2025-05-01T16:00:00Z",
    content: "Beautiful photo!",
    user_id: "7",
    user: users[6],
    parent_id: "104",
    parent: null,
    replies: [],
  },
  {
    id: "108",
    createdAt: "2025-05-01T17:00:00Z",
    content: "Code, snack, repeat.",
    user_id: "8",
    user: users[7],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "109",
    createdAt: "2025-05-01T18:00:00Z",
    content: "Peaceful yoga session this morning.",
    user_id: "9",
    user: users[8],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "110",
    createdAt: "2025-05-01T19:00:00Z",
    content: "Mixing a new track in the studio 🎧",
    user_id: "10",
    user: users[9],
    parent_id: null,
    parent: null,
    replies: [],
  },
];

// Set reply parent references
posts[5].parent = posts[0]; // Post 106 replies to Post 101
posts[6].parent = posts[3]; // Post 107 replies to Post 104

export { posts, users };
