const users = [
  {
    id: "1",
    username: "john_doe",
    name: "John Doe",
    image: "https://picsum.photos/seed/john/200",
    bio: "Tech enthusiast and coffee lover.",
  },
  {
    id: "2",
    username: "jane_smith",
    name: "Jane Smith",
    image: "https://picsum.photos/seed/jane/200",
    bio: "Traveler and food blogger.",
  },
  {
    id: "3",
    username: "mike_brown",
    name: "Mike Brown",
    image: "https://picsum.photos/seed/mike/200",
    bio: "Fitness coach and entrepreneur.",
  },
  {
    id: "4",
    username: "sara_white",
    name: "Sara White",
    image: "https://picsum.photos/seed/sara/200",
    bio: "Photographer and nature lover.",
  },
  {
    id: "5",
    username: "emma_green",
    name: "Emma Green",
    image: "https://picsum.photos/seed/emma/200",
    bio: "Writer and bookworm.",
  },
];

const posts = [
  {
    id: "101",
    createdAt: "2025-05-01T10:00:00Z",
    content: "Hello world! This is my first post.",
    user_id: "1",
    user: users[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "102",
    createdAt: "2025-05-01T11:00:00Z",
    content: "Loving the weather today!",
    user_id: "2",
    user: users[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "103",
    createdAt: "2025-05-01T12:00:00Z",
    content: "Just finished a great workout session.",
    user_id: "3",
    user: users[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "104",
    createdAt: "2025-05-01T13:00:00Z",
    content: "Check out this amazing sunset I captured!",
    user_id: "4",
    user: users[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "105",
    createdAt: "2025-05-01T14:00:00Z",
    content: "Currently reading an incredible book.",
    user_id: "5",
    user: users[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "106",
    createdAt: "2025-05-01T15:00:00Z",
    content: "Replying to @john_doe's first post!",
    user_id: "2",
    user: users[1],
    parent_id: "101",
    parent: posts[0],
    replies: [],
  },
  {
    id: "107",
    createdAt: "2025-05-01T16:00:00Z",
    content: "Great photo, Sara!",
    user_id: "5",
    user: users[4],
    parent_id: "104",
    parent: posts[3],
    replies: [],
  },
  {
    id: "108",
    createdAt: "2025-05-01T17:00:00Z",
    content: "Thanks, Emma!",
    user_id: "4",
    user: users[3],
    parent_id: "107",
    parent: posts[6],
    replies: [],
  },
  {
    id: "109",
    createdAt: "2025-05-01T18:00:00Z",
    content: "What book are you reading?",
    user_id: "3",
    user: users[2],
    parent_id: "105",
    parent: posts[4],
    replies: [],
  },
  {
    id: "110",
    createdAt: "2025-05-01T19:00:00Z",
    content: "It's called 'The Art of Coding'.",
    user_id: "5",
    user: users[4],
    parent_id: "109",
    parent: posts[8],
    replies: [],
  },
  {
    id: "111",
    createdAt: "2025-05-01T20:00:00Z",
    content: "Looks like a productive day!",
    user_id: "1",
    user: users[0],
    parent_id: "103",
    parent: posts[2],
    replies: [],
  },
  {
    id: "112",
    createdAt: "2025-05-01T21:00:00Z",
    content: "Absolutely! Feeling great.",
    user_id: "3",
    user: users[2],
    parent_id: "111",
    parent: posts[10],
    replies: [],
  },
  {
    id: "113",
    createdAt: "2025-05-01T22:00:00Z",
    content: "Anyone up for a hike tomorrow?",
    user_id: "4",
    user: users[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "114",
    createdAt: "2025-05-01T23:00:00Z",
    content: "Count me in!",
    user_id: "2",
    user: users[1],
    parent_id: "113",
    parent: posts[12],
    replies: [],
  },
  {
    id: "115",
    createdAt: "2025-05-02T00:00:00Z",
    content: "Sounds fun, let's do it!",
    user_id: "5",
    user: users[4],
    parent_id: "113",
    parent: posts[12],
    replies: [],
  },
];

export { posts, users };
